export {
  addBreadcrumb,
  addGlobalEventProcessor,
  captureEvent,
  captureException,
  captureMessage,
  configureScope,
  createTransport,
  FunctionToString,
  getCurrentHub,
  getHubFromCarrier,
  Hub,
  InboundFilters,
  makeMain,
  Scope,
  setContext,
  setExtra,
  setExtras,
  setTag,
  setTags,
  setUser,
  startTransaction,
  withScope,
} from "https://esm.sh/@sentry/core@7.7.0";
